### ISSUE TITLE
Uncaught exception on macOS with `setMenu`

### ISSUE THREAD

**Issue by AdrianoFerrari** [gingko/client#101]
User reported:
> This is what the dialog window said:

```
Uncaught Exception:
TypeError: Cannot read property 'setMenu' of null
at BrowserWindow.winHome.on (/Applications/Gingko.app/Contents/Resources/app.asar/electron.js:102219:13)
at emitOne (events.js:121:20)
at BrowserWindow.emit (events.js:211:7)
```

> I was looking at some other software and I clicked this window actually to close it, but before I gave any inputs, I got that.

**Comment by AdrianoFerrari** [comment]
Menu building code rewritten in [v2.2.0](https://github.com/gingko/client/tree/v2.2.0).
Closing.
