### ISSUE TITLE
Error when trying to open deleted file

### ISSUE THREAD

**Issue by dela3499** [gingko/client#122]
If you try to open a deleted document from 'Recent Documents' (`/home/carlos/Desktop/Untitled.gko` in this case), you get the error message: 

```javascript
Unhandled Promise Rejection
Error: Document data already deleted. Key /home/carlos/Desktop/Untitled.gko not found.
    at Object.removeDb (/tmp/.mount_gingkohXW6rD/resources/app.asar/electron.js:72817:11)
    at EventEmitter.ipcMain.on (/tmp/.mount_gingkohXW6rD/resources/app.asar/electron.js:121589:13)
    at <anonymous>
```

**Comment by dela3499** [comment]
Also, after creating a new document and trying to `Save As` to the previously-deleted file location, I get the following error:

```javascript
Unhandled Promise Rejection
Error: Could not create new swap folder.
/home/carlos/.config/Gingko/%home%carlos%Untitled.gko
Swap folder already exists.
Either document is already open, or it failed to close properly in the past.
    at swapCopy (/tmp/.mount_gingkof1cvwd/resources/app.asar/electron.js:224099:11)
    at <anonymous>
```

**Comment by AdrianoFerrari** [comment]
Thanks for the bug reports @dela3499 !

I moved your second one in this thread, to it's own issue:
